/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef STM32_DATA_GENERATOR_PRIVATE_H
#define STM32_DATA_GENERATOR_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.1.1"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	1
#define COMPANY_NAME	"成都伟智电联科技有限公司"
#define FILE_VERSION	"1.1.1.1"
#define FILE_DESCRIPTION	"STM32_Programer的数据生成器"
#define INTERNAL_NAME	"STM32_Data_Generator"
#define LEGAL_COPYRIGHT	"2019"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"STM32_Data_Generator"
#define PRODUCT_NAME	"STM32_Data_Generator"
#define PRODUCT_VERSION	"1.1.1.1"

#endif /*STM32_DATA_GENERATOR_PRIVATE_H*/
