/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef STM32_DATA_PROGRAMER_PRIVATE_H
#define STM32_DATA_PROGRAMER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"成都伟智电联科技有限公司"
#define FILE_VERSION	"1.0.0.0"
#define FILE_DESCRIPTION	"STM32_Programer烧录器"
#define INTERNAL_NAME	"STM32_Programer"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Data_Programer.exe"
#define PRODUCT_NAME	"STM32_Programer"
#define PRODUCT_VERSION	"1.0.0.0"

#endif /*STM32_DATA_PROGRAMER_PRIVATE_H*/
